# Generated by Django 3.2.5 on 2021-10-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='feedback_form',
        ),
        migrations.AddField(
            model_name='survey',
            name='allow_multiple_submissions',
            field=models.BooleanField(default=False, help_text='Users will be allowed to take the survey more than once'),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_feedback_survey',
            field=models.BooleanField(default=False, help_text="These responses are special and sent to the 'feedback' bucket"),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_vote_survey',
            field=models.BooleanField(default=False, help_text='These responses are special and responses are scored in LUX'),
        ),
    ]
