# Generated by Django 3.2.5 on 2021-11-29 19:43

from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasenote',
            name='date',
            field=models.DateField(default=survey.models.getToday),
        ),
    ]
