# Generated by Django 3.2.5 on 2021-10-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20211015_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='allow_multiple_submissions',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='is_feedback_survey',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='is_vote_survey',
        ),
        migrations.AddField(
            model_name='campaign',
            name='limit_one_submission',
            field=models.BooleanField(default=True, help_text='Users will only be allowed to take the survey once, every ## days.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='limit_one_submission_days',
            field=models.PositiveIntegerField(default=90, help_text='Allow the user to enter the pool of participants after these many days.'),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('vote', 'VotE'), ('feedback', 'Feedback'), ('other', 'other')], default='other', help_text='IMPORTANT: This determines how responses are tagged and used in LUX.', max_length=10),
        ),
    ]
