# Generated by Django 3.2.5 on 2022-01-03 16:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_releasenote_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='custom_project_name',
            field=models.CharField(blank=True, help_text='This will override the project name used in the selected project, for this campaign only/', max_length=128),
        ),
        migrations.AddField(
            model_name='campaign',
            name='url_match_action',
            field=models.CharField(blank=True, choices=[('exclude', 'Exclude'), ('include', 'Include')], default='', help_text='Include or exclude URLs that match the condition.', max_length=11),
        ),
        migrations.AddField(
            model_name='campaign',
            name='url_match_condition',
            field=models.CharField(blank=True, choices=[('contains', 'Contains'), ('exactMatch', 'Exact match'), ('startsWith', 'Starts with'), ('endsWith', 'Ends with')], default='', help_text='How to match the URL against the string', max_length=11),
        ),
        migrations.AddField(
            model_name='campaign',
            name='url_match_string',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='include_other_specify_answer',
            field=models.BooleanField(default=False, help_text="This will add an 'Other' option and automatically show a textarea write-in for the user to specify their answer"),
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='Question_name_here', help_text='Only used in admin, to easily identify this survey.', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionorder',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_order_campaign', to='survey.campaign'),
        ),
        migrations.AddField(
            model_name='surveyinvite',
            name='no_button_text',
            field=models.CharField(default='No thanks', max_length=128),
        ),
        migrations.AddField(
            model_name='surveyinvite',
            name='yes_button_text',
            field=models.CharField(default="Yes I'll take a brief survey", max_length=128),
        ),
        migrations.AddField(
            model_name='surveythankyou',
            name='feedback_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveythankyou',
            name='vote_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='limit_one_submission_days',
            field=models.PositiveIntegerField(default=90, help_text="Only used if 'Limit one submission' is enabled. Allows the user to enter the pool of participants after these many days."),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='response_count_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Disable the campaign when this many responses are received.', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='visitor_percent',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_number',
            field=models.FloatField(default=1),
        ),
    ]
