# Generated by Django 3.2.5 on 2021-10-25 20:55

from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20211025_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignuserinfo',
            name='reset_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='releasenote',
            name='date',
            field=models.DateTimeField(default=survey.models.getToday),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('vote', 'VotE'), ('feedback', 'Feedback'), ('other', 'Other')], default='other', help_text='IMPORTANT: This determines how responses are tagged and used in LUX.', max_length=10),
        ),
    ]
