# Generated by Django 3.2.5 on 2022-01-24 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0003_auto_20220103_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='small_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='url_match_regex',
            field=models.CharField(blank=True, help_text='Advanced regex matching for URLs. Use EITHER this one field OR the basic versions below.', max_length=500),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous', models.CharField(blank=True, help_text='Previous', max_length=64, null=True)),
                ('next', models.CharField(blank=True, help_text='Next', max_length=64, null=True)),
                ('submit', models.CharField(blank=True, help_text='Submit', max_length=64, null=True)),
                ('ibm_internal_privacy_statement', models.CharField(blank=True, help_text='IBM internal privacy statement', max_length=255, null=True, verbose_name='IBM internal privacy statement')),
                ('privacy_statement_url', models.URLField(blank=True, help_text='(URL for above link)', max_length=255, null=True)),
                ('catch_you_bad_time', models.CharField(blank=True, help_text='Catch you at a bad time?', max_length=128, null=True)),
                ('remind_me_later', models.CharField(blank=True, help_text='Remind me later', max_length=128, null=True)),
                ('expected_survey_time', models.CharField(blank=True, help_text='Expected survey time: 2 minutes', max_length=128, null=True)),
                ('email_me_a_link', models.CharField(blank=True, help_text='Email me a link', max_length=128, null=True)),
                ('send', models.CharField(blank=True, help_text='Send', max_length=64, null=True)),
                ('processing', models.CharField(blank=True, help_text='Processing', max_length=64, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translation_created_by', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translation_language', to='survey.language')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translation_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['language'],
            },
        ),
    ]
