# Generated by Django 3.2.5 on 2021-10-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_question_question_text_past_tense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text_past_tense',
            field=models.CharField(blank=True, help_text="This is used for 'take later' and email campaigns", max_length=255),
        ),
    ]
