# Generated by Django 3.2.5 on 2021-11-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_alter_question_question_text_past_tense'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='key_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
