# Generated by Django 3.2.5 on 2021-11-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_campaign_key_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='key_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
