# Generated by Django 3.2.5 on 2021-11-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_alter_campaign_key_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='uid',
            field=models.CharField(editable=False, max_length=25, unique=True),
        ),
    ]
