# Generated by Django 3.2.5 on 2021-11-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_alter_campaign_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='key_name',
            new_name='key',
        ),
    ]
