# Generated by Django 3.2.5 on 2021-11-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_rename_key_name_campaign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='uid',
            field=models.CharField(editable=False, max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('checkbox', 'Checkboxes'), ('date', 'Date'), ('email', 'Email'), ('message', 'Message'), ('number', 'Number'), ('radio', 'Radio buttons'), ('stars', 'Stars'), ('select', 'Select list'), ('selectmultiple', 'Select multiple'), ('textinput', 'Text input'), ('textarea', 'Textarea'), ('url', 'URL')], default='text', max_length=20),
        ),
    ]
