# Generated by Django 3.2.5 on 2021-11-05 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20211104_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='parent_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='parent_answer_action',
            field=models.CharField(choices=[('show', 'Show'), ('hide', 'Hide')], default='show', max_length=4),
        ),
        migrations.AddField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, help_text='Select a question to trigger', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_parent_question', to='survey.question'),
        ),
    ]
