# Generated by Django 3.2.5 on 2021-11-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20211105_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='slack_notification_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
