# Generated by Django 3.2.5 on 2021-11-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_campaign_slack_notification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='usabilla_migration_uid',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
