# Generated by Django 3.2.5 on 2021-11-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_campaign_usabilla_migration_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='lux_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='lux_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='key',
            field=models.CharField(blank=True, help_text='Auto-generated nice name identifier', max_length=128),
        ),
    ]
