# Generated by Django 3.2.5 on 2021-11-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_auto_20211111_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='trigger_type',
        ),
        migrations.AddField(
            model_name='campaign',
            name='survey_trigger_type',
            field=models.CharField(blank=True, choices=[('intercept', 'Intercept'), ('button', 'Button')], default='', help_text='If you are embedding this survey on a page, how do you want it to be triggered', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('checkbox', 'Checkboxes'), ('date', 'Date'), ('email', 'Email'), ('hidden', 'Hidden'), ('message', 'Message'), ('number', 'Number'), ('radio', 'Radio buttons'), ('stars', 'Stars'), ('select', 'Select list'), ('selectmultiple', 'Select multiple'), ('textinput', 'Text input'), ('textarea', 'Textarea'), ('url', 'URL')], default='text', max_length=20),
        ),
    ]
