# Generated by Django 3.2.5 on 2021-11-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20211115_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionorder',
            name='sort_order',
            field=models.FloatField(default=1),
        ),
    ]
