# Generated by Django 3.2.5 on 2021-11-18 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_alter_questionorder_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionorder',
            options={'ordering': ['page', 'question_number']},
        ),
        migrations.RenameField(
            model_name='questionorder',
            old_name='sort_order',
            new_name='question_number',
        ),
    ]
