# Generated by Django 3.2.5 on 2021-11-21 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_auto_20211117_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='parent_answer_action',
            field=models.CharField(choices=[('show', 'Show this question'), ('hide', 'Hide this question')], default='show', max_length=4),
        ),
        migrations.AlterField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, help_text="Select the question who's answer should show/hide this question", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_parent_question', to='survey.question'),
        ),
    ]
