# Generated by Django 3.2.5 on 2021-11-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_auto_20211121_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='feed_to_lux',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='lux_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='lux_id',
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('vote', 'VotE'), ('feedback', 'Feedback'), ('other', 'Other')], default='other', help_text='IMPORTANT: This determines how responses are tagged and displayed.', max_length=10),
        ),
    ]
