# Generated by Django 3.2.5 on 2021-11-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_auto_20211123_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='usabilla_migration_uid',
        ),
    ]
