# Generated by Django 3.2.5 on 2021-12-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_alter_question_include_other_specify_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='replaceMe', help_text='Only used in admin, to easily identify this survey.', max_length=128),
            preserve_default=False,
        ),
    ]
