# Generated by Django 3.2.5 on 2021-12-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0025_question_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveythankyou',
            name='feedback_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveythankyou',
            name='vote_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='limit_one_submission_days',
            field=models.PositiveIntegerField(default=90, help_text="Only used if 'Limit one submission' is enabled. Allows the user to enter the pool of participants after these many days."),
        ),
    ]
