# Generated by Django 3.2.5 on 2021-12-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0026_auto_20211207_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='url_match_regex',
            new_name='url_match_string',
        ),
        migrations.AddField(
            model_name='campaign',
            name='custom_project_name',
            field=models.CharField(blank=True, help_text='This will override the project name used in the selected project, for this campaign only/', max_length=128),
        ),
        migrations.AddField(
            model_name='campaign',
            name='url_match_action',
            field=models.CharField(blank=True, choices=[('exclude', 'Exclude'), ('include', 'Include')], default='', help_text='Include or exclude URLs that match the condition.', max_length=11),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='url_match_condition',
            field=models.CharField(blank=True, choices=[('contains', 'Contains'), ('exactMatch', 'Exact match'), ('startsWith', 'Starts with'), ('endsWith', 'Ends with')], default='', help_text='How to match the URL against the string', max_length=11),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_number',
            field=models.FloatField(default=1),
        ),
    ]
