# Generated by Django 3.2.5 on 2021-12-13 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0027_auto_20211208_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinvite',
            name='no_button_text',
            field=models.CharField(default='No thanks', max_length=128),
        ),
        migrations.AddField(
            model_name='surveyinvite',
            name='yes_button_text',
            field=models.CharField(default="Yes I'll take a brief survey", max_length=128),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='visitor_percent',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
