# Generated by Django 3.2.5 on 2022-01-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0028_auto_20211213_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='small_button',
            field=models.BooleanField(default=False),
        ),
    ]
